parameters:
#    ns_color_admin_sonata.example.class: NS\ColorAdminSonataBundle\Example

services:
   ns_ace.form.hidden_parent_extension:
      class: NS\ColorAdminSonataBundle\Form\Extensions\InputWrapperExtension
      tags:
        - { name: form.type_extension, alias: form, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

#    ns_color_admin_sonata.example:
#        class: %ns_color_admin_sonata.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
